### ISSUE TITLE
示例的项目跑不起来

### ISSUE THREAD

**Issue by 1120040377** [alipay/sofa-node#5]
/root/rpc-server/node_modules/jar2proxy-alpha/lib/java/javahome.js:98
  throw new Error((javahome.toolsPath || 'JAVA_HOME') + ' Can`t be found or not correct!');
  ^

Error: lib/tools.jar Can`t be found or not correct!
    at Object.<anonymous> (/root/rpc-server/node_modules/jar2proxy-alpha/lib/java/javahome.js:98:9)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/rpc-server/node_modules/jar2proxy-alpha/lib/java/jar.js:5:33)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpc-server@1.0.0 rpc: `egg-rpc-generator`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpc-server@1.0.0 rpc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-17T08_29_26_685Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpc-server@1.0.0 init: `npm run rpc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpc-server@1.0.0 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-17T08_29_26_703Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpc-server@1.0.0 start: `npm run init && egg-scripts start --daemon --title=egg-server-rpc-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpc-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-17T08_29_26_719Z-debug.log

**Comment by killagu** [comment]
Java 配置了吗？ JAVA_HOME 这个环境变量没有

**Comment by leoner** [comment]
这个依赖 java 环境, 需要配置下 JAVA_HOME
